vich_uploader:
    db_driver: orm
    mappings:
        stuff_image:
            uri_prefix: /uploads/images/stuff
            upload_destination: '%kernel.project_dir%/public/uploads/images/stuff'
            namer:
                service: Vich\UploaderBundle\Naming\SmartUniqueNamer

            inject_on_load: true
            delete_on_update: true
            delete_on_remove: true